from typing import Any, Protocol

from backend.app.repositories.search import ItemSearchCriteria, ItemSearchPage, ItemSort


class GsemRepository(Protocol):
    """실제 DB 어댑터가 구현해야 하는 조회 계약."""

    def get_dashboard_overview(self) -> dict[str, Any]: ...
    def get_filter_options(self) -> dict[str, Any]: ...
    def search_items(
        self,
        criteria: ItemSearchCriteria,
        sort: ItemSort,
        page: int,
        size: int,
    ) -> ItemSearchPage: ...
    def get_item_by_id(self, item_id: int) -> dict[str, Any] | None: ...
    def get_delivery_schedules(self) -> list[dict[str, Any]]: ...
    def get_change_events(self) -> list[dict[str, Any]]: ...
    def get_replacement_graph(self, root_item_id: int) -> dict[str, Any] | None: ...
